document.addEventListener('DOMContentLoaded', () => {
  const $ = id => document.getElementById(id);
  const root = document.documentElement;
  const defaultState = () => ({lang:'fr',title:'De quel côté êtes-vous ?',subtitle:'Which Side Are You On?',rows:[],nextId:1,boxCount:5,showNumbers:true,showBrand:true,colors:{accent:'#d01020',bg:'#fafaf8',ink:'#0c0c0c'}});
  let state=defaultState(), history=[], editing=false, activeImage=null;
  const copy={fr:{builder:'Which side are you on?',content:'Contenu',title:'Titre',subtitle:'Sous-titre',questions:'Questions',addRow:'Ajouter une question',appearance:'Apparence',boxes:'Choix par question',numbers:'Afficher les numéros',numbersHint:'Afficher 1, 2, 3… dans les cases',branding:'Marque WASLL',brandingHint:'Afficher le watermark sur l’image',accent:'Accent',background:'Fond',ink:'Texte',clear:'Effacer',export:'Exporter PNG',emptyTitle:'Aucune question',emptyText:'Créez votre première question pour commencer.',left:'Côté gauche',right:'Côté droit',upload:'Ajouter une image',remove:'Supprimer',up:'Monter',down:'Descendre',editOnCanvas:'Cliquez directement sur le visuel pour le modifier.',helpText:'Cliquez sur un côté ou une image pour le personnaliser.',undo:'Annuler',exportEmpty:'Ajoutez au moins une question avant d’exporter.',exportError:'Impossible de générer l’image.'},en:{builder:'Which side are you on?',content:'Content',title:'Title',subtitle:'Subtitle',questions:'Questions',addRow:'Add a question',appearance:'Appearance',boxes:'Choices per question',numbers:'Show choice numbers',numbersHint:'Show 1, 2, 3… in the boxes',branding:'WASLL branding',brandingHint:'Show the watermark on the image',accent:'Accent',background:'Background',ink:'Text',clear:'Clear',export:'Export PNG',emptyTitle:'No questions yet',emptyText:'Create your first question to get started.',left:'Left side',right:'Right side',upload:'Add an image',remove:'Delete',up:'Move up',down:'Move down',editOnCanvas:'Click directly on the visual to edit it.',helpText:'Click a side or an image to customize it.',undo:'Undo',exportEmpty:'Add at least one question before exporting.',exportError:'Could not generate the image.'}};
  const titleInput=$('title-input'), subtitleInput=$('subtitle-input'), posterTitle=$('poster-title'), posterSubtitle=$('poster-subtitle'), rowsEl=$('rows'), empty=$('empty-state');
  function t(k){return copy[state.lang][k]||k}
  function clone(v){return JSON.parse(JSON.stringify(v))}
  function snapshot(){return clone(state)}
  function pushHistory(){const s=snapshot(),last=history.at(-1);if(last&&JSON.stringify(last)===JSON.stringify(s))return;history.push(s);if(history.length>50)history.shift();updateUndo()}
  function updateUndo(){const b=$('undo-btn');b.disabled=!history.length;b.title=t('undo');b.setAttribute('aria-label',t('undo'))}
  function syncChrome(){titleInput.value=state.title;subtitleInput.value=state.subtitle;root.style.setProperty('--red',state.colors.accent);root.style.setProperty('--black',state.colors.ink);root.style.setProperty('--white',state.colors.bg);$('accent-input').value=state.colors.accent;$('bg-input').value=state.colors.bg;$('ink-input').value=state.colors.ink;$('accent-value').textContent=state.colors.accent.toUpperCase();$('bg-value').textContent=state.colors.bg.toUpperCase();$('ink-value').textContent=state.colors.ink.toUpperCase();$('show-numbers').checked=state.showNumbers;$('show-brand').checked=state.showBrand;$('watermark').style.display=state.showBrand?'':'none';syncChoiceButtons()}
  function applyLanguage(){document.querySelectorAll('[data-i18n]').forEach(e=>e.textContent=t(e.dataset.i18n));document.querySelectorAll('#language-switch .language-btn').forEach(b=>b.classList.toggle('active',b.dataset.lang===state.lang));titleInput.placeholder=state.lang==='fr'?'Votre titre…':'Your title…';subtitleInput.placeholder=state.lang==='fr'?'Votre sous-titre…':'Your subtitle…';syncHeadings();renderRows();updateUndo()}
  function syncHeadings(){posterTitle.textContent=state.title.trim()||(state.lang==='fr'?'De quel côté êtes-vous ?':'Which side are you on?');posterSubtitle.textContent=state.subtitle.trim()}
  function editHeading(key){const el=$(key==='title'?'poster-title':'poster-subtitle');if(el.querySelector('input'))return;const old=state[key];pushHistory();editing=true;el.contentEditable='true';el.focus();const range=document.createRange();range.selectNodeContents(el);range.collapse(false);getSelection().removeAllRanges();getSelection().addRange(range);el.addEventListener('blur',finish,{once:true});el.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();el.blur()}if(e.key==='Escape'){el.textContent=old;el.blur()}});function finish(){delete el.contentEditable;const value=el.textContent.trim();state[key]=value;syncChrome();editing=false}}
  $('poster-title').addEventListener('click',()=>editHeading('title'));$('poster-subtitle').addEventListener('click',()=>editHeading('subtitle'));
  [titleInput,subtitleInput].forEach(input=>{input.addEventListener('focus',pushHistory);input.addEventListener('input',()=>{if(input===titleInput)state.title=input.value;else state.subtitle=input.value;syncHeadings()})});
  document.querySelectorAll('#language-switch .language-btn').forEach(btn=>btn.addEventListener('click',()=>{if(btn.dataset.lang===state.lang)return;pushHistory();const old=state.lang;const oldTitle=old==='fr'?'De quel côté êtes-vous ?':'Which side are you on?';if(state.title===oldTitle)state.title=btn.dataset.lang==='fr'?'De quel côté êtes-vous ?':'Which side are you on?';state.lang=btn.dataset.lang;syncChrome();applyLanguage()}));
  function addRow(){pushHistory();const id=state.nextId++;state.rows.push({id,left:'',right:'',leftDetail:'',rightDetail:'',leftImage:null,rightImage:null});renderRows();setTimeout(()=>focusSide(id,'left'),0)}
  function moveRow(id,dir){const i=state.rows.findIndex(r=>r.id===id),j=i+dir;if(i<0||j<0||j>=state.rows.length)return;pushHistory();[state.rows[i],state.rows[j]]=[state.rows[j],state.rows[i]];renderRows()}
  function deleteRow(id){pushHistory();state.rows=state.rows.filter(r=>r.id!==id);renderRows()}
  function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  function rowMarkup(row,index){const boxes=Array.from({length:state.boxCount},(_,i)=>`<div class="choice-box">${state.showNumbers?i+1:''}</div>`).join('');return `<div class="side left" data-side="left" data-row="${row.id}"><div class="image-wrap" data-image-side="left" data-row="${row.id}">${row.leftImage?`<img class="side-image" src="${row.leftImage}" alt="">`:`<div class="side-placeholder"><i class="bi bi-image"></i></div>`}</div><div class="side-text"><div class="side-label editable" data-field="left" data-row="${row.id}" contenteditable="true" spellcheck="false">${esc(row.left)||`<span class="placeholder-text">${esc(t('left'))}</span>`}</div><div class="side-detail editable" data-field="leftDetail" data-row="${row.id}" contenteditable="true" spellcheck="false">${esc(row.leftDetail)}</div></div></div><div class="boxes">${boxes}</div><div class="side right" data-side="right" data-row="${row.id}"><div class="image-wrap" data-image-side="right" data-row="${row.id}">${row.rightImage?`<img class="side-image" src="${row.rightImage}" alt="">`:`<div class="side-placeholder"><i class="bi bi-image"></i></div>`}</div><div class="side-text"><div class="side-label editable" data-field="right" data-row="${row.id}" contenteditable="true" spellcheck="false">${esc(row.right)||`<span class="placeholder-text">${esc(t('right'))}</span>`}</div><div class="side-detail editable" data-field="rightDetail" data-row="${row.id}" contenteditable="true" spellcheck="false">${esc(row.rightDetail)}</div></div></div><div class="row-controls"><button class="mini-btn" data-action="up" type="button" title="${t('up')}"><i class="bi bi-chevron-up"></i></button><button class="mini-btn" data-action="down" type="button" title="${t('down')}"><i class="bi bi-chevron-down"></i></button><button class="mini-btn delete" data-action="delete" type="button" title="${t('remove')}"><i class="bi bi-trash3"></i></button></div>${index<state.rows.length-1?'<div class="row-divider"></div>':''}`}
  function renderRows(){rowsEl.innerHTML='';$('row-count').textContent=state.rows.length;empty.classList.toggle('empty-state-hidden',state.rows.length>0);state.rows.forEach((row,index)=>{const el=document.createElement('article');el.className='side-row';el.id=`row-${row.id}`;el.innerHTML=rowMarkup(row,index);rowsEl.appendChild(el);bindRow(el,row)})}
  function bindRow(el,row){el.querySelectorAll('.editable').forEach(node=>{node.addEventListener('focus',()=>{if(!node.dataset.history){pushHistory();node.dataset.history='1'}});node.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();node.blur()};if(e.key==='Escape'){node.textContent=row[node.dataset.field]||'';node.blur()}});node.addEventListener('blur',()=>{const field=node.dataset.field;row[field]=node.textContent.trim();node.removeAttribute('data-history');renderPreview(row,el)})});el.querySelectorAll('.image-wrap').forEach(w=>w.addEventListener('click',e=>{e.stopPropagation();activeImage={row,side:w.dataset.imageSide};$('image-picker').click()}));el.querySelector('[data-action="up"]').addEventListener('click',()=>moveRow(row.id,-1));el.querySelector('[data-action="down"]').addEventListener('click',()=>moveRow(row.id,1));el.querySelector('[data-action="delete"]').addEventListener('click',()=>deleteRow(row.id))}
  function renderPreview(row,el){const update=(side)=>{const label=el.querySelector(`.side.${side} .side-label`),detail=el.querySelector(`.side.${side} .side-detail`);label.innerHTML=esc(row[side])||`<span class="placeholder-text">${esc(t(side))}</span>`;detail.textContent=row[`${side}Detail`]||''};update('left');update('right')}
  function focusSide(id,side){document.querySelector(`#row-${id} .side.${side} .side-label`)?.focus()}
  function syncChoiceButtons(){document.querySelectorAll('#box-count-wrap button').forEach(b=>b.classList.toggle('active',Number(b.dataset.count)===state.boxCount))}
  document.querySelectorAll('#box-count-wrap button').forEach(b=>b.addEventListener('click',()=>{const n=Number(b.dataset.count);if(n===state.boxCount)return;pushHistory();state.boxCount=n;syncChoiceButtons();renderRows()}));
  ['show-numbers','show-brand'].forEach(id=>$(id).addEventListener('change',e=>{pushHistory();if(id==='show-numbers')state.showNumbers=e.target.checked;else{state.showBrand=e.target.checked;$('watermark').style.display=state.showBrand?'':'none'}renderRows()}));
  [['accent-input','accent'],['bg-input','bg'],['ink-input','ink']].forEach(([id,key])=>$(id).addEventListener('input',e=>{if(!$(id).dataset.history){pushHistory();$(id).dataset.history='1'}state.colors[key]=e.target.value;root.style.setProperty(key==='accent'?'--red':key==='bg'?'--white':'--black',e.target.value);$(`${id.replace('-input','')}-value`).textContent=e.target.value.toUpperCase()}));
  document.querySelectorAll('#language-switch .language-btn').forEach(()=>{});
  $('appearance-toggle').addEventListener('click',()=>{const b=$('appearance-toggle'),p=$('appearance-panel'),open=b.getAttribute('aria-expanded')==='true';b.setAttribute('aria-expanded',String(!open));p.hidden=open});
  $('add-row').addEventListener('click',addRow);$('empty-add').addEventListener('click',addRow);$('undo-btn').addEventListener('click',()=>{const previous=history.pop();if(!previous)return;state=previous;syncChrome();applyLanguage()});
  $('clear-all').addEventListener('click',()=>{if(!state.rows.length)return;if(confirm(t('clearConfirm')||'Clear all questions?')){pushHistory();state.rows=[];renderRows()}});
  $('mobile-settings').addEventListener('click',()=>{$('sidebar').classList.add('mobile-open');$('mobile-overlay').classList.add('open')});$('mobile-overlay').addEventListener('click',closeMobile);$('sidebar-close').addEventListener('click',closeMobile);function closeMobile(){$('sidebar').classList.remove('mobile-open');$('mobile-overlay').classList.remove('open')}
  const picker=document.createElement('input');picker.type='file';picker.id='image-picker';picker.accept='image/*';picker.hidden=true;document.body.appendChild(picker);picker.addEventListener('change',()=>{const file=picker.files?.[0];if(!file||!activeImage)return;pushHistory();const reader=new FileReader();reader.onload=e=>{activeImage.row[`${activeImage.side}Image`]=e.target.result;picker.value='';activeImage=null;renderRows()};reader.readAsDataURL(file)});
  async function exportPng(){if(!state.rows.length){showStatus(t('exportEmpty'));return}const btn=$('toolbar-export');btn.disabled=true;try{const canvas=await window.html2canvas($('poster'),{scale:3,useCORS:true,backgroundColor:null,logging:false,ignoreElements:el=>el.classList?.contains('row-controls')});const a=document.createElement('a');a.download=`wasll-side-${Date.now()}.png`;a.href=canvas.toDataURL('image/png');a.click();showStatus(t('export'))}catch(err){console.error(err);showStatus(t('exportError'))}finally{btn.disabled=false}}
  $('toolbar-export').addEventListener('click',exportPng);
  function showStatus(text){let s=$('export-status');if(!s){s=document.createElement('div');s.id='export-status';s.className='export-status';document.body.appendChild(s)}s.textContent=text;s.classList.add('show');clearTimeout(showStatus.timer);showStatus.timer=setTimeout(()=>s.classList.remove('show'),1800)}
  syncChrome();applyLanguage();
});
